# Generated by Django 4.2 on 2025-10-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Mensaje', models.CharField(max_length=100)),
                ('FechaRegistro', models.DateTimeField(verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name_plural': 'Formulario',
            },
        ),
    ]
