# Generated by Django 4.2 on 2025-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
